# Generated by Django 3.2.5 on 2021-07-12 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategeryName', models.CharField(max_length=50)),
                ('Slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SingerName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SongName', models.CharField(max_length=1000)),
                ('Lyrics', models.CharField(max_length=1000)),
                ('SongWriter', models.CharField(max_length=1000)),
                ('YoutubeId', models.CharField(max_length=20)),
                ('Short', models.TextField()),
                ('DateTime', models.DateField()),
                ('Album', models.CharField(blank=True, max_length=50, null=True)),
                ('Slug', models.SlugField(blank=True, max_length=40, null=True, unique=True)),
                ('Views', models.IntegerField()),
                ('Genere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.genere')),
            ],
        ),
    ]
