# Generated by Django 3.2.5 on 2021-07-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_singer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='Slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
