# Generated by Django 3.2.5 on 2021-07-12 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_singer_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='Slug',
        ),
    ]
