# Generated by Django 3.2.5 on 2021-07-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_singer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='SingerName',
            field=models.ManyToManyField(to='home.Singer'),
        ),
    ]
