# Generated by Django 3.2.5 on 2021-07-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_song_singername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='SingerName',
            new_name='singerName',
        ),
    ]
