# Generated by Django 3.2.5 on 2021-07-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_singername_song_singername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singer',
            old_name='SingerName',
            new_name='Name',
        ),
    ]
