# Generated by Django 3.2.5 on 2021-07-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_singername_singer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='Views',
            field=models.IntegerField(default=0),
        ),
    ]
