# Generated by Django 3.2.5 on 2021-07-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_views_song_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='Lyrics',
            field=models.TextField(),
        ),
    ]
