# Generated by Django 3.2.5 on 2021-07-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_song_lyrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_Name', models.CharField(default='Hello World', max_length=50)),
                ('Site_decs', models.CharField(default='site Name', max_length=101)),
                ('Favicon', models.ImageField(upload_to='static/Favicon')),
                ('Short_story', models.TextField()),
                ('Telegram_url', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterModelOptions(
            name='genere',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='singer',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-pk']},
        ),
    ]
